name: Deploy Coffee Shop App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 \
          | docker login --username AWS \
          --password-stdin $(aws ecr describe-repositories \
          --query "repositories[0].repositoryUri" \
          --output text)

      - name: Build Image
        run: docker build -t coffee-app .

      - name: Tag & Push
        run: |
          REPO=$(aws ecr describe-repositories \
          --query "repositories[0].repositoryUri" \
          --output text)
          docker tag coffee-app:latest $REPO:latest
          docker push $REPO:latest